### ISSUE TITLE
Running the Action script locally using nektos/act fails 

### ISSUE THREAD

**Issue by itaymesh** [julienloizelet/magento2-ddev-installation#10]
Hi @julienloizelet, 
First, I would like to thank you for creating and sharing the very useful GitHub Action. 

I have been trying to test it locally using https://github.com/nektos/act. 

The process runs fine until a certain point, and then it fails. 
Following is the relevant output.

Do you know what's causing it and how it could be resolved? 

Much appreciate it!

Itay
 
```
....
| Created a new local CA 💥
| The local CA is now installed in the system trust store! ⚡️
| 
| Could not connect to a docker provider. Please start or install a docker provider.
| For install help go to: https://ddev.readthedocs.io/en/latest/users/install/
[Coding standards/Static test suite]   ❌  Failure - Main Install DDEV
[Coding standards/Static test suite] exitcode '1': failure
[Coding standards/Static test suite]   ⚙  ::set-output:: m2_url=
[Coding standards/Static test suite]   ❌  Failure - Main Install Magento 2
[Coding standards/Static test suite] exitcode '1': failure
[Coding standards/Static test suite] ⭐ Run Post Install Magento 2
[Coding standards/Static test suite]   🐳  docker cp src=/Users/itay/.cache/act/julienloizelet-magento2-ddev-installation@v2.1.0/ dst=/var/run/act/actions/julienloizelet-magento2-ddev-installation@v2.1.0/
[Coding standards/Static test suite]   🐳  docker exec cmd=[chown -R 1001:1001 /var/run/act/actions/julienloizelet-magento2-ddev-installation@v2.1.0/] user=0 workdir=
[Coding standards/Static test suite]   ✅  Success - Post Install Magento 2
[Coding standards/Static test suite] 🏁  Job failed
Error: Job 'Static test suite' failed

...
```

**Comment by julienloizelet** [comment]
Hi @itaymesh,
Thanks for your message.

Reading your error message suggests that there is something wrong with Docker.

Did you install Docker on your machine ? ([as explained here](https://github.com/nektos/act#necessary-prerequisites-for-running-act))

Thanks

**Comment by itaymesh** [comment]
Yes, of course. 
I am running Docker for Mac with Intel Chip 

![image](https://user-images.githubusercontent.com/493197/231102090-15541a0c-e935-48f7-b8c6-f2516453f3ac.png)

**Comment by julienloizelet** [comment]
Ok!

Well, I never tried to test locally with  `nektos/act`. And I'm using a linux setup.

But I will try it asap to see if I can reproduce the bug. 

Thanks

**Comment by julienloizelet** [comment]
Hi @itaymesh, 

I tried ACT and got the same error.

I opened an issue in the ACT repo to find out more:  https://github.com/nektos/act/issues/1731

Thanks

**Comment by itaymesh** [comment]
Hi @julienloizelet 
Thank you for letting me know. I see we have yet to get a response.
What would you preferay for testing GitHub Actions?

**Comment by julienloizelet** [comment]
> Hi @julienloizelet Thank you for letting me know. I see we have yet to get a response. What would you preferay for testing GitHub Actions?

Hi,
most of the time, I just use a `workflow_dispatch` workflow to manually trigger an action.

As I am working on Linux, I assume that if it works on my machine, it will work in the GitHub runner :) 

For a more advanced debug (when it is not working as expected), I sometimes use this [action](https://github.com/mxschmitt/action-tmate) to enter in the runner with an ssh session.

**Comment by julienloizelet** [comment]
No response from nektos: https://github.com/nektos/act/issues/1731. I close this one.
